### ISSUE TITLE
Not found in npm repository

### ISSUE THREAD

**Issue by crstnmac** [raivieiraadriano92/react-native-template-codeapp#1]
![tyutyynshot](https://user-images.githubusercontent.com/20360870/104797073-62b1a700-57e1-11eb-87bc-d306223b0106.jpg)

Package not found in npm register

**Comment by raivieiraadriano92** [comment]
Hi @crstnmac  , i hope your fine.
First i would like thank you for use this package.
I will try help you.
Could send to me what command you are trying run, please?

In here i run `npx react-native init MyAwesomeApp --template react-native-template-codeapp` and works fine.

**Comment by crstnmac** [comment]
I had run the same comnand

**Comment by raivieiraadriano92** [comment]
@crstnmac , by any chance do you have installed the legacy `react-native-cli`?
Because this template just works with new CLI globally.
I added a new section in README about this, please check it and let me know if work for you.

**Comment by raivieiraadriano92** [comment]
https://github.com/raivieiraadriano92/react-native-template-codeapp#note-on-the-legacy-cli

**Comment by crstnmac** [comment]
Oh yeah. Thankyou ☺️

**Comment by raivieiraadriano92** [comment]
@crstnmac  it's a pleasure to help you.
Can I mark this issue as resolved?

**Comment by crstnmac** [comment]
> @crstnmac  it's a pleasure to help you.
> Can I mark this issue as resolved?

Yes
